on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup lfs
        run: |
          echo "${{ secrets.credentials }}" | IFS=---- read -ra CREDENTIALS
          for CREDENTIAL in "${CREDENTIALS[@]}"; do
            echo "$CREDENTIAL" | git credential-store store
          done

          ./setup.bash

      - name: Check files
        run: |
          sha256sum -c checksums.txt
