on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup lfs
        run: |
          echo "${{ secrets.lfs_credentials }}" | while IFS= read -r line; do
            if [[ "$line" == "----" ]]; then
              if [[ -n "$buffer" ]]; then
                echo "$buffer" | git credential-store store
                buffer=""
              fi
            else
              buffer+="$line"$'\n'
            fi
          done
          echo "$buffer" | git credential-store store

          ./setup.bash

      - name: Check files
        run: |
          sha256sum -c checksums.txt
