on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup lfs
        run: |
          echo "${{ secrets.lfs_credentials }}" >> ~/.git-credentials
          git config --global credential.helper store

          git lfs install
          git lfs pull

      - name: Check files
        run: |
          sha256sum -c checksums.txt
